name: Validations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true

    - name: Unit Tests
      run: |
        cd test
        go clean -testcache
        go test -v ./...
    
  Lint-Check:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v3
        - uses: actions/checkout@v3
        - uses: golangci/golangci-lint-action@v3.4.0
          with:
            skip-pkg-cache: true
