name: Validations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Validations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
        cache: true

    - run: go mod tidy

    - name: Unit Tests
      run: |
        cd test
        go clean -testcache
        go test -v ./...
    
    - name: Lint
      uses: golangci/golangci-lint-action@v3.4.0
